### ISSUE TITLE
Test with Helm instead of Kustomize

### ISSUE THREAD

**Issue by roguh** [edge-experiments/argocd-scalability#4]
Hello, I'd like to try this experiment using Helm instead of Kustomize. Any advice?

**Comment by waltforme** [comment]
Just trying to follow, in which specific place/phase do you want to use Helm instead?

**Comment by roguh** [comment]
I see you use Kustomize in some scenarios (such as scenario 2 in the [article](https://itnext.io/sync-10-000-argo-cd-applications-in-one-shot-bfcda04abe5b)) and that caused performance problems.

I'd like to try using an ApplicationSet that creates ArgoCD Applications which would use Helm, such as this app:

```
    metadata:
      name: '{{site}}'
    spec:
      project: default
      destination:
        # server: '{{k8s_cluster.address}}'
        server: 'https://kubernetes.default.svc'
        namespace: '{{site}}'
      source:
        repoURL: git@github.com:...
        targetRevision: dev
        path: './per-site/'
        helm:
          values: |
            environment: "{{softwareVersions}}"
```

Thanks for the response, I wasn't sure if it's the best place to contact you about this.
